/*
 * This source file was generated by the Gradle 'init' task
 */
public static void main(String[] args) {
    Scanner scanner = new Scanner(System.in);
    // Creamos la cuenta inicial (Requerimiento: Crear cuenta)
    Cuenta miCuenta = new Cuenta("Usuario Alke", 0.0);

    boolean salir = false;
    while (!salir) {
        System.out.println("\n--- ALKE WALLET ---");
        System.out.println("1. Ver saldo");
        System.out.println("2. Ingresar dinero (Depositar)");
        System.out.println("3. Retirar dinero");
        System.out.println("4. Salir");
        int opcion = scanner.nextInt();

        switch (opcion) {
            case 1:
                miCuenta.verSaldo();
                break;
            case 2:
                System.out.println("Monto a ingresar:");
                int montoIngreso = scanner.nextInt();
                // Usamos la lógica de interfaces
                System.out.println("Seleccione medio de origen: 1.Paypal 2.Bitcoin");
                int medio = scanner.nextInt();
                if(medio == 1) miCuenta.ingresarFondos(new Paypal("user@mail.com"), montoIngreso);
                else miCuenta.ingresarFondos(new Bitcoin("bc1q..."), montoIngreso);
                break;
            case 3:
                System.out.println("Monto a retirar:");
                double montoRetiro = scanner.nextDouble();
                miCuenta.retirarFondos(montoRetiro);
                break;
            case 4:
                salir = true;
                break;
        }
    }
}